enable-magisk-update = false
parallel-jobs = 1
rebuild-all-on-update = true
remove-rv-integrations-checks = true
compression-level = 9
patches-version = "dev"
cli-version = "dev"
riplib = true
arch = "arm64-v8a"
build-mode = "apk"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon='mnt' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=revanced"
riplib = true
version = "20.21.37"

[YouTube-Music-Extended]
app-name = "YouTube Music"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon='mnt' -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=revanced"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
riplib = true
version = "8.30.54"

[Spotify]
enabled = false
build-mode = "apk"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
version = "auto"
